spring:
  datasource:
    jndi-name: jdbc/Library
  jpa:
    database-platform: org.hibernate.dialect.MySQLInnoDBDialect
    properties:
      current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
      dialect: org.hibernate.dialect.MySQL8Dialect
      format_sql: true
    show-sql: true
  security:
    user:
      name: user
      password: password
logging:
  file: /Users/leokooper/git/SpringHibernateTraining/spring-hibernate-demo/temp/log.txt
  pattern:
    file: "%d:{HH:mm:ss} %-5p [%c] - %m%n"

  level:
    ROOT: warn
    org.springframework: warn
    org.springframework.security: warn
    org.hibernate: warn
    org.hibernate.type.descriptor.sql: trace

